/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/Conference-table-b.glb -o ./app/vr-conference/components/ConferenceTable.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ConferenceTable(props) {
  const { nodes, materials } = useGLTF('models/Conference-table-b.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.62, 1.63]} rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[14.37, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.poshtu} position={[-14.37, 2.46, -21.36]} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.payeh} position={[-14.37, 2.72, -21.49]} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.kafsh} position={[-14.34, 2.34, -17.6]} />
          </group>
          <group position={[-3.84, 0, 8.19]} rotation={[0, -1.57, 0]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.kafsh} position={[-29.9, 2.27, 0.51]} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.poshtu} position={[-29.88, 2.46, -3.64]} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.payeh} position={[-29.88, 2.72, -3.77]} />
          </group>
          <group position={[0, -0.82, -0.01]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[0, 4.74, -20.28]} scale={[0.46, 1.14, 0.95]} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.002']} position={[0, 5.03, -20.27]} scale={[0.71, 1, 1]} />
          </group>
          <mesh geometry={nodes.Object_15.geometry} material={materials['poshtu.001']} position={[-0.25, -5.99, -20.58]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Conference-table-b.glb')
